server:
  port: 8888

rocketmq:
  name-server: rmqNamesrv:9876
  producer:
    group: test-producer-group1
    send-message-timeout: 300000


demo:
  consumer:
    group: demo-consumer-group1
    topic: demo-topic-for-rmq

